name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Build package
      run: |
        pipenv run build
    - name: Test with pytest
      run: |
        pipenv run pytest
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
